// Data contoh (dummy) untuk keperluan desain UI/UX.
// Tanggal dihitung relatif terhadap hari ini agar tampilan dashboard & agenda
// selalu terlihat "hidup" kapan pun prototipe ini dibuka.

import { addDays } from './utils'
import { STATUS } from './status'

const today = new Date()
today.setHours(0, 0, 0, 0)

function atTime(dayOffset, hour, minute = 0) {
  const d = addDays(today, dayOffset)
  d.setHours(hour, minute, 0, 0)
  return d
}

export const PEJABAT = [
  { id: 'p1', nama: 'Dr. Ir. Ahmad Fauzi, M.T.', jabatan: 'Direktur Utama', unit: 'Direktorat Utama' },
  { id: 'p2', nama: 'Siti Nurhaliza, S.E., M.M.', jabatan: 'Kepala Bagian Keuangan', unit: 'Bagian Keuangan' },
  { id: 'p3', nama: 'Budi Santoso, S.Kom.', jabatan: 'Kepala Divisi Teknologi Informasi', unit: 'Divisi Teknologi Informasi' },
  { id: 'p4', nama: 'Rina Kusuma Wardani, S.H.', jabatan: 'Kepala Bagian Hukum & Humas', unit: 'Bagian Hukum & Humas' },
  { id: 'p5', nama: 'Drs. Hendra Wijaya, M.M.', jabatan: 'Sekretaris Perusahaan', unit: 'Sekretariat Perusahaan' },
  { id: 'p6', nama: 'Dewi Anggraini, S.Psi.', jabatan: 'Kepala Bagian SDM', unit: 'Bagian SDM' },
  { id: 'p7', nama: 'Muhammad Iqbal, S.T.', jabatan: 'Kepala Bagian Operasional', unit: 'Bagian Operasional' },
  { id: 'p8', nama: 'Yulianti Puspita, S.E.', jabatan: 'Kepala Bagian Pengadaan', unit: 'Bagian Pengadaan' },
]

export const LOKASI_LIST = [
  'Ruang Rapat Utama Lt. 3',
  'Ruang Tamu VIP Lt. 1',
  'Ruang Rapat Lt. 2',
  'Aula Serbaguna',
  'Ruang Kerja Direktur',
  'Ruang Rapat Lt. 4',
]

function pejabatById(id) {
  return PEJABAT.find((p) => p.id === id)
}

let seq = 0
function kunjungan({
  nama,
  instansi,
  jabatanTamu,
  telepon,
  email,
  rombongan = 1,
  tujuan,
  keterangan,
  pejabatId,
  lokasi,
  hari,
  jamMulai,
  jamSelesai,
  status,
  catatanPetugas = '',
  dibuatSebelum = 2,
}) {
  seq += 1
  const mulai = atTime(hari, jamMulai[0], jamMulai[1])
  const selesai = atTime(hari, jamSelesai[0], jamSelesai[1])
  return {
    id: `KJG-2026-${String(seq).padStart(4, '0')}`,
    nama,
    instansi,
    jabatanTamu,
    telepon,
    email,
    rombongan,
    tujuan,
    keterangan,
    pejabat: pejabatById(pejabatId),
    lokasi,
    mulai,
    selesai,
    status,
    catatanPetugas,
    dibuatPada: atTime(hari - dibuatSebelum, 8, 30),
  }
}

export const KUNJUNGAN = [
  kunjungan({
    nama: 'Agus Prasetyo',
    instansi: 'PT Sinergi Cipta Karya',
    jabatanTamu: 'Manajer Proyek',
    telepon: '0812-3456-7801',
    email: 'agus.prasetyo@sinergicipta.co.id',
    rombongan: 3,
    tujuan: 'Audiensi kerja sama proyek infrastruktur',
    keterangan: 'Membahas peluang kerja sama pembangunan infrastruktur kawasan tahap II.',
    pejabatId: 'p1',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: -9,
    jamMulai: [9, 0],
    jamSelesai: [10, 30],
    status: STATUS.SELESAI,
    dibuatSebelum: 3,
  }),
  kunjungan({
    nama: 'Ratna Dewi Lestari',
    instansi: 'Universitas Sebelas Maret',
    jabatanTamu: 'Dosen Fakultas Teknik',
    telepon: '0813-2233-4455',
    email: 'ratna.dewi@staff.uns.ac.id',
    rombongan: 5,
    tujuan: 'Kunjungan studi banding manajemen mutu',
    keterangan: 'Studi banding penerapan sistem manajemen mutu ISO 9001 untuk keperluan akreditasi.',
    pejabatId: 'p6',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: -8,
    jamMulai: [13, 0],
    jamSelesai: [14, 30],
    status: STATUS.SELESAI,
    dibuatSebelum: 4,
  }),
  kunjungan({
    nama: 'Bambang Setiawan',
    instansi: 'Dinas Komunikasi dan Informatika',
    jabatanTamu: 'Kepala Seksi Layanan Publik',
    telepon: '0812-9988-7766',
    email: 'bambang.s@diskominfo.go.id',
    rombongan: 2,
    tujuan: 'Sosialisasi program pemerintah',
    keterangan: 'Sosialisasi program digitalisasi layanan publik terpadu.',
    pejabatId: 'p3',
    lokasi: 'Ruang Rapat Lt. 4',
    hari: -7,
    jamMulai: [10, 0],
    jamSelesai: [11, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 2,
  }),
  kunjungan({
    nama: 'Farah Amelia',
    instansi: 'Kantor Berita Antara',
    jabatanTamu: 'Jurnalis',
    telepon: '0857-1122-3344',
    email: 'farah.amelia@antaranews.com',
    rombongan: 1,
    tujuan: 'Wawancara liputan media',
    keterangan: 'Permohonan wawancara terkait kinerja triwulan II.',
    pejabatId: 'p4',
    lokasi: 'Ruang Tamu VIP Lt. 1',
    hari: -6,
    jamMulai: [9, 0],
    jamSelesai: [9, 30],
    status: STATUS.DITOLAK,
    catatanPetugas: 'Jadwal bentrok dengan agenda pimpinan yang bersangkutan.',
    dibuatSebelum: 1,
  }),
  kunjungan({
    nama: 'Joko Purnomo',
    instansi: 'CV Mitra Abadi Sejahtera',
    jabatanTamu: 'Direktur',
    telepon: '0811-4433-2211',
    email: 'joko.purnomo@mitraabadi.co.id',
    rombongan: 2,
    tujuan: 'Penjajakan kerja sama riset',
    keterangan: 'Penjajakan kerja sama riset dan pengembangan produk baru.',
    pejabatId: 'p7',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: -6,
    jamMulai: [14, 0],
    jamSelesai: [15, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 3,
  }),
  kunjungan({
    nama: 'Indah Permatasari',
    instansi: 'Bank Mandiri Cabang Solo',
    jabatanTamu: 'Relationship Manager',
    telepon: '0812-6677-8899',
    email: 'indah.permatasari@bankmandiri.co.id',
    rombongan: 2,
    tujuan: 'Konsultasi layanan perbankan korporat',
    keterangan: 'Penawaran layanan cash management untuk transaksi operasional.',
    pejabatId: 'p2',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: -5,
    jamMulai: [11, 0],
    jamSelesai: [12, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 2,
  }),
  kunjungan({
    nama: 'Wahyu Hidayat',
    instansi: 'PT Adhi Karya (Persero) Tbk',
    jabatanTamu: 'Site Manager',
    telepon: '0813-5566-7788',
    email: 'wahyu.hidayat@adhikarya.co.id',
    rombongan: 4,
    tujuan: 'Rapat koordinasi proyek konstruksi',
    keterangan: 'Koordinasi progres pembangunan gedung tahap akhir.',
    pejabatId: 'p7',
    lokasi: 'Aula Serbaguna',
    hari: -4,
    jamMulai: [9, 30],
    jamSelesai: [11, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 3,
  }),
  kunjungan({
    nama: 'Nurul Fadhilah',
    instansi: 'Politeknik Negeri Semarang',
    jabatanTamu: 'Kepala Program Studi',
    telepon: '0857-3344-5566',
    email: 'nurul.fadhilah@polines.ac.id',
    rombongan: 3,
    tujuan: 'Penjajakan kerja sama magang mahasiswa',
    keterangan: 'Pembahasan kuota dan penempatan magang semester ganjil.',
    pejabatId: 'p6',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: -4,
    jamMulai: [13, 0],
    jamSelesai: [14, 0],
    status: STATUS.DIBATALKAN,
    catatanPetugas: 'Dibatalkan oleh tamu karena berhalangan hadir.',
    dibuatSebelum: 5,
  }),
  kunjungan({
    nama: 'Eko Prabowo',
    instansi: 'Kementerian PUPR',
    jabatanTamu: 'Staf Ahli',
    telepon: '0811-2299-3388',
    email: 'eko.prabowo@pu.go.id',
    rombongan: 6,
    tujuan: 'Kunjungan kerja & silaturahmi pejabat baru',
    keterangan: 'Kunjungan kerja dalam rangka silaturahmi dengan jajaran direksi baru.',
    pejabatId: 'p1',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: -3,
    jamMulai: [10, 0],
    jamSelesai: [11, 30],
    status: STATUS.SELESAI,
    dibuatSebelum: 6,
  }),
  kunjungan({
    nama: 'Maya Sari Dewi',
    instansi: 'Yayasan Peduli Bangsa',
    jabatanTamu: 'Ketua Yayasan',
    telepon: '0812-7788-9900',
    email: 'maya.saridewi@pedulibangsa.org',
    rombongan: 2,
    tujuan: 'Penyerahan proposal kerja sama CSR',
    keterangan: 'Penyerahan proposal program CSR bidang pendidikan.',
    pejabatId: 'p5',
    lokasi: 'Ruang Tamu VIP Lt. 1',
    hari: -2,
    jamMulai: [9, 0],
    jamSelesai: [10, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 2,
  }),
  kunjungan({
    nama: 'Rudi Hartono',
    instansi: 'PT Telkom Indonesia',
    jabatanTamu: 'Account Manager',
    telepon: '0813-8899-0011',
    email: 'rudi.hartono@telkom.co.id',
    rombongan: 3,
    tujuan: 'Presentasi produk & solusi IT',
    keterangan: 'Presentasi solusi konektivitas dan keamanan jaringan korporat.',
    pejabatId: 'p3',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: -2,
    jamMulai: [13, 30],
    jamSelesai: [15, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 3,
  }),
  kunjungan({
    nama: 'Anita Wijayanti',
    instansi: 'Koperasi Sejahtera Mandiri',
    jabatanTamu: 'Bendahara',
    telepon: '0857-6655-4433',
    email: 'anita.wijayanti@kopsejahtera.id',
    rombongan: 1,
    tujuan: 'Konsultasi pembinaan koperasi',
    keterangan: 'Konsultasi terkait pembinaan dan pelaporan keuangan koperasi.',
    pejabatId: 'p2',
    lokasi: 'Ruang Rapat Lt. 4',
    hari: -1,
    jamMulai: [10, 0],
    jamSelesai: [10, 30],
    status: STATUS.DITOLAK,
    catatanPetugas: 'Dokumen persyaratan belum lengkap, diarahkan menjadwalkan ulang.',
    dibuatSebelum: 1,
  }),
  kunjungan({
    nama: 'Taufik Hidayat',
    instansi: 'PT Bank Rakyat Indonesia',
    jabatanTamu: 'Branch Manager',
    telepon: '0811-3344-5577',
    email: 'taufik.hidayat@bri.co.id',
    rombongan: 4,
    tujuan: 'Audit eksternal tahunan',
    keterangan: 'Pelaksanaan audit eksternal laporan keuangan tahun berjalan.',
    pejabatId: 'p2',
    lokasi: 'Ruang Rapat Lt. 4',
    hari: -1,
    jamMulai: [8, 30],
    jamSelesai: [12, 0],
    status: STATUS.SELESAI,
    dibuatSebelum: 7,
  }),
  kunjungan({
    nama: 'Sri Wahyuni',
    instansi: 'Dinas Lingkungan Hidup',
    jabatanTamu: 'Kepala Bidang',
    telepon: '0812-4455-6677',
    email: 'sri.wahyuni@dlh.go.id',
    rombongan: 2,
    tujuan: 'Rapat koordinasi program lingkungan',
    keterangan: 'Koordinasi program pengelolaan limbah kawasan industri.',
    pejabatId: 'p7',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: -1,
    jamMulai: [9, 0],
    jamSelesai: [10, 0],
    status: STATUS.MENUNGGU,
    dibuatSebelum: 1,
  }),
  kunjungan({
    nama: 'Dedi Kurniawan',
    instansi: 'Universitas Gadjah Mada',
    jabatanTamu: 'Wakil Dekan Bidang Kerja Sama',
    telepon: '0813-1122-9900',
    email: 'dedi.kurniawan@ugm.ac.id',
    rombongan: 7,
    tujuan: 'Kunjungan studi banding tata kelola',
    keterangan: 'Studi banding penerapan tata kelola dan reformasi birokrasi.',
    pejabatId: 'p1',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: 0,
    jamMulai: [9, 0],
    jamSelesai: [11, 0],
    status: STATUS.BERLANGSUNG,
    dibuatSebelum: 5,
  }),
  kunjungan({
    nama: 'Fajar Nugroho',
    instansi: 'PT Pupuk Sriwidjaja',
    jabatanTamu: 'Supervisor Distribusi',
    telepon: '0857-2233-1100',
    email: 'fajar.nugroho@pusri.co.id',
    rombongan: 2,
    tujuan: 'Rapat koordinasi distribusi',
    keterangan: 'Koordinasi jadwal distribusi pupuk bersubsidi wilayah.',
    pejabatId: 'p7',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: 0,
    jamMulai: [7, 30],
    jamSelesai: [8, 30],
    status: STATUS.SELESAI,
    dibuatSebelum: 2,
  }),
  kunjungan({
    nama: 'Putri Ramadhani',
    instansi: 'Dinas Pendidikan Provinsi Jawa Tengah',
    jabatanTamu: 'Kepala Seksi Kurikulum',
    telepon: '0812-5566-3322',
    email: 'putri.ramadhani@disdik-jateng.go.id',
    rombongan: 3,
    tujuan: 'Sosialisasi program pemerintah',
    keterangan: 'Sosialisasi kurikulum merdeka untuk jenjang menengah kejuruan.',
    pejabatId: 'p6',
    lokasi: 'Ruang Rapat Lt. 4',
    hari: 0,
    jamMulai: [13, 0],
    jamSelesai: [14, 0],
    status: STATUS.MENUNGGU,
    dibuatSebelum: 1,
  }),
  kunjungan({
    nama: 'Agung Wibisono',
    instansi: 'PT Bina Karya Sejahtera',
    jabatanTamu: 'Manajer Pemasaran',
    telepon: '0813-9900-1122',
    email: 'agung.wibisono@binakarya.co.id',
    rombongan: 2,
    tujuan: 'Presentasi produk & solusi IT',
    keterangan: 'Presentasi solusi perangkat lunak pengelolaan aset.',
    pejabatId: 'p3',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: 0,
    jamMulai: [15, 30],
    jamSelesai: [16, 30],
    status: STATUS.MENUNGGU,
    dibuatSebelum: 1,
  }),
  kunjungan({
    nama: 'Lestari Handayani',
    instansi: 'Asosiasi Pengusaha Indonesia (Apindo)',
    jabatanTamu: 'Sekretaris Umum',
    telepon: '0811-6677-8800',
    email: 'lestari.handayani@apindo.or.id',
    rombongan: 4,
    tujuan: 'Audiensi kebijakan investasi daerah',
    keterangan: 'Audiensi membahas kemudahan perizinan investasi daerah.',
    pejabatId: 'p1',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: 0,
    jamMulai: [14, 0],
    jamSelesai: [15, 30],
    status: STATUS.DISETUJUI,
    dibuatSebelum: 4,
  }),
  kunjungan({
    nama: 'Yuni Kartika',
    instansi: 'Universitas Sebelas Maret',
    jabatanTamu: 'Kepala Hubungan Masyarakat',
    telepon: '0857-4433-2200',
    email: 'yuni.kartika@uns.ac.id',
    rombongan: 2,
    tujuan: 'Wawancara liputan media kampus',
    keterangan: 'Liputan profil kerja sama industri untuk majalah kampus.',
    pejabatId: 'p4',
    lokasi: 'Ruang Tamu VIP Lt. 1',
    hari: 1,
    jamMulai: [9, 0],
    jamSelesai: [9, 45],
    status: STATUS.DISETUJUI,
    dibuatSebelum: 3,
  }),
  kunjungan({
    nama: 'Hari Setiabudi',
    instansi: 'Kementerian PUPR',
    jabatanTamu: 'Kepala Balai Wilayah',
    telepon: '0812-8899-4400',
    email: 'hari.setiabudi@pu.go.id',
    rombongan: 5,
    tujuan: 'Rapat koordinasi proyek nasional',
    keterangan: 'Koordinasi lanjutan proyek strategis nasional tahap III.',
    pejabatId: 'p1',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: 1,
    jamMulai: [13, 0],
    jamSelesai: [14, 30],
    status: STATUS.DISETUJUI,
    dibuatSebelum: 6,
  }),
  kunjungan({
    nama: 'Sinta Marlina',
    instansi: 'PT Telkom Indonesia',
    jabatanTamu: 'Manajer Solusi Enterprise',
    telepon: '0813-2244-6688',
    email: 'sinta.marlina@telkom.co.id',
    rombongan: 3,
    tujuan: 'Presentasi solusi transformasi digital',
    keterangan: 'Presentasi peta jalan transformasi digital tahun mendatang.',
    pejabatId: 'p3',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: 2,
    jamMulai: [9, 30],
    jamSelesai: [11, 0],
    status: STATUS.DISETUJUI,
    dibuatSebelum: 4,
  }),
  kunjungan({
    nama: 'Bayu Aji Saputro',
    instansi: 'Politeknik Negeri Semarang',
    jabatanTamu: 'Ketua Jurusan Teknik Elektro',
    telepon: '0857-5566-7799',
    email: 'bayu.aji@polines.ac.id',
    rombongan: 4,
    tujuan: 'Penjajakan kerja sama magang mahasiswa',
    keterangan: 'Penjajakan program magang bersertifikat semester genap.',
    pejabatId: 'p6',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: 3,
    jamMulai: [13, 0],
    jamSelesai: [14, 0],
    status: STATUS.MENUNGGU,
    dibuatSebelum: 2,
  }),
  kunjungan({
    nama: 'Diah Ayu Lestari',
    instansi: 'Bank Mandiri Cabang Solo',
    jabatanTamu: 'Kepala Cabang',
    telepon: '0811-7788-9911',
    email: 'diah.ayu@bankmandiri.co.id',
    rombongan: 2,
    tujuan: 'Audiensi program kemitraan UMKM',
    keterangan: 'Audiensi program pembiayaan kemitraan untuk pelaku UMKM binaan.',
    pejabatId: 'p2',
    lokasi: 'Ruang Rapat Utama Lt. 3',
    hari: 4,
    jamMulai: [9, 0],
    jamSelesai: [10, 0],
    status: STATUS.DISETUJUI,
    dibuatSebelum: 5,
  }),
  kunjungan({
    nama: 'Arief Rahman',
    instansi: 'CV Mitra Abadi Sejahtera',
    jabatanTamu: 'Direktur Operasional',
    telepon: '0813-3344-9988',
    email: 'arief.rahman@mitraabadi.co.id',
    rombongan: 2,
    tujuan: 'Rapat lanjutan kerja sama riset',
    keterangan: 'Rapat lanjutan pembahasan kontrak kerja sama riset produk.',
    pejabatId: 'p7',
    lokasi: 'Ruang Rapat Lt. 2',
    hari: 6,
    jamMulai: [13, 30],
    jamSelesai: [14, 30],
    status: STATUS.DISETUJUI,
    dibuatSebelum: 3,
  }),
  kunjungan({
    nama: 'Novi Handayani',
    instansi: 'Yayasan Peduli Bangsa',
    jabatanTamu: 'Sekretaris',
    telepon: '0857-8899-0022',
    email: 'novi.handayani@pedulibangsa.org',
    rombongan: 3,
    tujuan: 'Audiensi program CSR lanjutan',
    keterangan: 'Audiensi evaluasi dan perluasan program CSR bidang pendidikan.',
    pejabatId: 'p5',
    lokasi: 'Ruang Tamu VIP Lt. 1',
    hari: 9,
    jamMulai: [9, 30],
    jamSelesai: [10, 30],
    status: STATUS.MENUNGGU,
    dibuatSebelum: 2,
  }),
]

export function getKunjunganById(id) {
  return KUNJUNGAN.find((k) => k.id === id)
}

export const TUJUAN_OPTIONS = Array.from(new Set(KUNJUNGAN.map((k) => k.tujuan)))
